jon = User.create(name: "Jon")
# kai = User.create(name: "Kai")

business = Interest.create(name: "business")
entertainment = Interest.create(name: "entertainment")
general = Interest.create(name: "general")
health = Interest.create(name: "health")
science = Interest.create(name: "science")
sports = Interest.create(name: "sports")
technology = Interest.create(name: "technology")
